CREATE PROC FI_SP_IncBenefV2
    @NOME          VARCHAR (50) ,
    @CPF           VARCHAR (15) ,
    @IDCLIENTE     BIGINT
AS
BEGIN
	INSERT INTO CLIENTES (NOME, CPF, IDCLIENTE) 
	VALUES (@NOME,  @CPF, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END